### ISSUE TITLE
Автозапуск приложений

### ISSUE THREAD

**Issue by d-r-q** [aleksey-zhidkov/smart-switcher#2]
Надо сделать автозапуск приложений, в случае если получена команда на активацию окна отсутствующего на данном воркспейсе

**Comment by aleksey-zhidkov** [comment]
Сделано в e4f5ca6b5150aef255be127cf559e00d64f5b8d8

**Comment by d-r-q** [comment]
Сделано в 75aed9b7d9b369be81dd2d40338e584851f84484
